=pod

=head1 NAME

Module::Build::Chado - Module::Build extension for Chado database based perl modules

=head1 VERSION

version 0.0011

=head1 AUTHOR

Siddhartha Basu <biosidd@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Siddhartha Basu.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

